services:
  idm-fortune-service:
    build: .
    ports:
      - "8888:8888"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PRINTER_API_HOST=${PRINTER_API_HOST}
    volumes:
      - ./fortune_images:/app/fortune_images
      - ./server.py:/app/server.py
      - ./img:/app/img
      - ./cards:/app/cards
      - ./idm.json:/app/idm.json
    # depends_on:
    #   - printer-api
    restart: unless-stopped

  # printer-api:
  #   build: ./mock_printer
  #   ports:
  #     - "8080:8080"
  #   restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - idm-fortune-service
    restart: unless-stopped
    network_mode: "host"
    environment:
      - CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
